# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clocking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
            ],
        ),
    ]
