# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puncher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkPoint',
            fields=[
                ('checkpoint_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='clocking',
            old_name='staff_id',
            new_name='checkPoint_id',
        ),
        migrations.RenameField(
            model_name='clocking',
            old_name='id',
            new_name='punch_id',
        ),
        migrations.AddField(
            model_name='clocking',
            name='person_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
